### ISSUE TITLE
4.8.0 breaks SSE connections proxying

### ISSUE THREAD

**Issue by netkin-paris** [saucelabs/sauce-connect-docker#43]
Hello,

For information your last version (4.8.0) breaks SSE connections (your proxy seems to wait for the end of the http connection before sending any packet).

![image](https://user-images.githubusercontent.com/1146493/168578752-2453b9ed-800d-4fa4-a352-bde2d5c6c58e.png)

Switching back to 4.7.0 restores SSE connections proxying.

Regards

**Comment by netkin-paris** [comment]
The issue was with testcafe proxying, closing.

**Comment by robbytx** [comment]
@netkin-paris our tests that use SSE (Server-Sent Events) started failing this week with the release of 4.8.0 because no response was received.  Meanwhile, using 4.7.1 fixes the issue as you said, so I agree with your original issue, and I don't understand what you mean by "testcafe proxying".  I'm curious if you think this issue should be reopened.

**Comment by netkin-paris** [comment]
Hello @robbytx, after further investigation, we got the following results : 
- testcafe hammerhead proxying (different from testcafe outgoing proxy options) + saucelabs connect proxying => sse connection fails
- testcafe hammerhead proxying alone on our dev machine => sse working
- saucelab connect proxing alone (via saucelabs live testing) => sse working

Testcafe does not hammerhead-proxy XHR requests (it would be useless in our case), but still proxies SSE requests, which is unwanted in our case, but we could not find any option to disable it.

As a workaround, we decided that it was a good occasion to implement long polling fallback, because SSE is never guaranted, for example when corporate proxies buffer the response to an https request until the end of content. 

This is an improvement to the reliability of our product, but it also makes e2e tests slower.

In your case, with 4.7.1, is SSE working using saucelabs live testing ? and/or with a testing framework ?

**Comment by robbytx** [comment]
Using 4.7.1 reliably works with SauceLabs automated testing for me, while using 4.8.0 does not -- the SSE connections in the Network tab show "Pending" indefinitely.  I've not tried with live testing.

My configuration is Selenium (Java) tests connected to SauceLabs connecting (via Sauce Connect Proxy running in Docker) to `http://<local-ip-address>`, which is running Nginx serving our web assets and proxying to our backend API (which handles the SSE connection).  We've been running in this configuration for nearly 3 years, and it only broke in the last week or so when our configuration started using 4.8.0.

For now, I've rolled back to 4.7.1 to fix our tests, but I would like to ensure that this issue is reported and addressed, since it seems clearly a regression in the 4.8 version.

**Comment by waggledans** [comment]
@robbytx it seems that the issue is with Sauce Connect Proxy 4.8.0 and not docker image-specific. I think it's better to follow up on this through a Sauce labs support ticket.

**Comment by waggledans** [comment]
I think a quick workaround might be adding `--experimental no-proxy` to the commandline. for example:

```
$ docker run \
       --detach \
       -e SAUCE_USERNAME=${SAUCE_USERNAME} \
       -e SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY} \
       -p 8032:8032 \
       -t saucelabs/sauce-connect:4.8.0 \
       --tunnel-name my-docker-tunnel \
       --experimental no-proxy
```

Could u plz confirm it works @robbytx ?

**Comment by robbytx** [comment]
I can confirm that adding `--experimental no-proxy` with version 4.8.0 does permit the SSE connections to work.

**Comment by waggledans** [comment]
Thank you @robbytx.
So I think a temporary solution is to update the 4.8.0 docker tag with `--experimental no-proxy` (it's hardcoded in the image). This way, users can use 4.8.0. In the meantime, a support ticket to Sauce Labs should address the root cause.
